const ADD_TO_CART = "ADD_TO_CART",
  INCREASE_AMOUNT = "INCREASE_AMOUNT",
  DECREASE_AMOUNT = "DECREASE_AMOUNT",
  REMOVE_FROM_CART = "REMOVE_FROM_CART";

export { ADD_TO_CART, REMOVE_FROM_CART, INCREASE_AMOUNT, DECREASE_AMOUNT };
